export const API = {
  LOGIN: '/auth/login',
  AUTH: '/auth',
  REGISTER: '/user/register',
  USER: '/user',
  SEARCH: '/user/find-user/search',
  NOTI: '/noti',
  FOLLOW: '/follow',
  ALLPOST: '/post',
  POST: '/post/all',
  COMMENT: '/comment',
  SUGGEST: '/follow/suggest',
  PROFILE: '/user',
  PROFILEPHOTO: '/post/profile',
  PROFILECOMMENT: '/comment',
  PROFILEREACT: '/react-post',
  FOLLOWER: '/follow/find/follower',
  FOLLOWING: 'follow/find/following',
  MESSAGE: '/message',
  CONVERSATION: '/conversation',
  UPLOADIMAGE: '',
  CREATEPOST: '/post',
  CREATEMEDIA: '/post-media',
  REACTCOMMENT: '/react-cmt',
  CHECKFOLLOW: '/follow/check',
  EDITPOST: '/post/update/content',
  ACCESS: '/access-log',
  POSTALL: '/post/post-all',
  POSTONE: '/post/one-post',
};

export const LIST_API_NOT_AUTHENTICATE = [API.LOGIN, API.REGISTER];
