export const PATH = {
  HOME: '',
  PRIVATE: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  EXPLORE: '/explore',
  POST: '/p',
  REELS: '/reels/:media_id',
  MESSENGER: '/direct',
  MESSAGE: '/direct/t/:chatCode',
  INBOX: '/direct/inbox',
  PROFILE: '/profile/:userCode',
  EDITPROFILE: '/account/edit',
  ADMIN: '/admin',
  STAR: '*',
};
